spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
    h2: #콘솔 활성화
      console:
        enabled: true
        settings:
          web-allow-others: true  # 추가t
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 109083233023-09mpq3hmsbkqm549ibss70dqnstug2jt.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

