# 워크플로의 이름 지정
name: CI

#워크 플로가 시작될 조건 지정
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest #실행환경 지정
    #실행 스텝 지정
    steps:
      - uses: action/checkout@v3

      - uses: action/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build wiht Gradle
        run: ./gradlew clean build